### PR TITLE
Added support for Telco Systems T5C

### PR DESCRIPTION
**Pull request by jnorell**
Added support for Telco Systems T5C following
http://www.shrubbery.net/pipermail/rancid-discuss/2009-July/004062.html

### CODE REVIEW

**Comment by jnorell** [comment]
Any chance you'd accept this?  I goofed up by not having this in a separate branch; I have another vendor I want to add as well but can't create a clean pull request for it, it includes these commits as well, so I'm holding off on it for now.

Thanks...

**Comment by dotwaffle** [comment]
Unfortunately, github has a merge conflict. Any chance you can rebase/merge with latest HEAD and re-submit? I'll then auto-merge it because it looks quite useful.

Strongly consider submitting upstream too!

**Comment by jnorell** [comment]
Conflicts are resolved, merge away...

**Comment by jnorell** [comment]
status/reminder on this request (I have 2 more immediately following this one, and working on 1 more)

**Comment by dotwaffle** [comment]
So sorry for missing this -- I've been doing a lot of travelling recently and completely missed the notification. Merging as requested!

**Pull request merged**
