### PR TITLE
Support for pfSense firewalls

### PR DESCRIPTION
**Pull request by jnorell**

### CODE REVIEW

**Comment by jnorell** [comment]
this one is now conflict free

thanks....

**Comment by dotwaffle** [comment]
Thanks once more!

Strongly consider submitting this upstream too -- when I get some free time (hah!) I'm planning on submitting a lot of this upstream in one big chunk.

**Comment by buraglio** [comment]
I am glad someone else found this useful and found time to update it to pfsense 2.x. Interested in looking at my alurancid? =) I get weekly emails about it and have never had time to address them. https://github.com/buraglio/alurancid It works for my needs but is a pretty popular request for upstream support.

**Comment by jnorell** [comment]
Sorry @buraglio, don't have any equipment which would use alurancid.  It's pretty simple to put that in a rancid-git pull request on github, which I could do real quick, but sure couldn't test/vouch for it working.

**Pull request merged**
